# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spk_saw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot_Kondisi_Keuangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis_bobot_kondisi', to='spk_saw.Jenis')),
                ('perhitungan_kondisi_keuangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kondisi_keuangan_bobot', to='spk_saw.Perhitungan_Kondisi_Keuangan')),
            ],
            options={
                'verbose_name_plural': 'Bobot Kondisi Keuangan',
            },
        ),
    ]
