# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spk_saw', '0002_bobot_kondisi_keuangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot_Investasi_Balik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis_bobot_investasi', to='spk_saw.Jenis')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name_plural': 'Bobot Investasi Balik',
            },
        ),
        migrations.CreateModel(
            name='Bobot_Profil_Usaha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis_bobot_profil', to='spk_saw.Jenis')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name_plural': 'Bobot Profil Usaha',
            },
        ),
        migrations.CreateModel(
            name='Hasil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-hasil'],
                'verbose_name_plural': 'Hasil Perangkingan',
            },
        ),
        migrations.AlterModelOptions(
            name='bobot_kondisi_keuangan',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Bobot Kondisi Keuangan'},
        ),
        migrations.AlterModelOptions(
            name='perhitungan_investasi_balik',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Perhitungan Investasi Balik'},
        ),
        migrations.AlterModelOptions(
            name='perhitungan_kondisi_keuangan',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Perhitungan Kondisi Keuangan'},
        ),
        migrations.AlterModelOptions(
            name='perhitungan_profil_usaha',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Perhitungan Profil Usaha'},
        ),
        migrations.AlterField(
            model_name='bobot_kondisi_keuangan',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis_bobot_kondisi', to='spk_saw.Jenis'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='perhitungan_investasi_balik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investasi_balik_hasil', to='spk_saw.Perhitungan_Investasi_Balik'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='perhitungan_kondisi_keuangan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kondisi_keuangan_hasil', to='spk_saw.Perhitungan_Kondisi_Keuangan'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='perhitungan_profil_usaha',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_usaha_hasil', to='spk_saw.Perhitungan_Profil_Usaha'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='perusahaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perusahaan_hasil', to='spk_saw.Perusahaan'),
        ),
        migrations.AddField(
            model_name='bobot_profil_usaha',
            name='perhitungan_profil_usaha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_usaha_bobot', to='spk_saw.Perhitungan_Profil_Usaha'),
        ),
        migrations.AddField(
            model_name='bobot_investasi_balik',
            name='perhitungan_investasi_balik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investasi_balik_bobot', to='spk_saw.Perhitungan_Investasi_Balik'),
        ),
    ]
