# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spk_saw', '0003_auto_20180704_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_usaha',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='bagi_hasil',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='bunga',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='cash_flow',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='jenis_usaha',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='proyeksi_keuangan',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='tingkat_revenue',
            name='jenis',
        ),
        migrations.AddField(
            model_name='inverstasi_balik',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invstasi_balik_jenis', to='spk_saw.Jenis'),
        ),
        migrations.AddField(
            model_name='kondisi_keuangan',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kondisi_keuangan_jenis', to='spk_saw.Jenis'),
        ),
        migrations.AddField(
            model_name='profile_usaha',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_usaha_jenis', to='spk_saw.Jenis'),
        ),
        migrations.AlterField(
            model_name='jenis',
            name='bobot',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
