# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_saw', '0005_auto_20181009_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
